### ISSUE TITLE
Adding people who are not enrolled in DS8

### ISSUE THREAD

**Issue by AndrejGitHub** [berkeleydatascience/history-connector#4]
Dear Sam and all;

To follow-up on adding people not enrolled in DS8. You showed us that this could be done and I wanted to double-check with two cases: a math-history double major who wants to take H88 but not DS8, and a colleague from the D-lab, Michael Schultz, whose help with programming and with pedagogy I would appreciate.

Carl mentioned that there were a handful of students who enrolled in connectors and took the main course last semester, so I am assuming that adding undergrads can be done, and wanted to double-check. As for the second person, Cathryn has worked with Michael, who teaches intro stats in Soc. and is the D-Lab. When he and I worked today after our meeting on a Notebook, it was quite slow as he does not have access to Tables (though the commands are close to Pandas so traces of progress exist).

I spoke briefly to Chris and Elaine about this after the 11am meeting, and they noted correctly that adding people could be problematic for maintaining the integrity of the DS infrastructure. I am of course grateful for all of your help, and at present I am looking for all the help I can get, and Michael has a good sense of what I would like to communicate to students as, let's say, a fellow historically oriented social scientist.

So, if there are elegant solutions for both cases, wonderful -- could both be added with the status of that undergrads have? -- and if more info would be helpful, please let me know.

All the best,

Andrej

**Comment by SamLau95** [comment]
If it's adding these two users to our Jupyterhub environment, that can be easily be done.

Not sure about actually enrolling in the class, although my hunch is that you'd like these two to be enrolled you can make it happen.
